language: node_js
node_js:
 - "stable"
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database jubilee_test;' -U postgres
script:
 - npm install
 - npm run migrate
 - npm run coveralls
notifications:
  email: false
